name: Continuous Deployment to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@master

    - name: Move to deploy dir
      run: mkdir -p GHPAGES && mv index.html GHPAGES/
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # PERSONAL_TOKEN: ${{ secrets.GH_PAT }}
        # GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./GHPAGES
